packages:
  - .

allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true

overrides:
  prosemirror-model: 1.25.8
  prosemirror-view: 1.41.9
  prosemirror-state: 1.4.4
  prosemirror-transform: 1.12.0
